name: validate

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  validate_csv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run image
      # https://github.com/Data-Liberation-Front/csvlint.rb/blob/master/README.md
      run: docker run --rm -tv $GITHUB_WORKSPACE:/workspace gsscogs/csvlint ash -c 'for f in /workspace/*.csv; do csvlint $f --schema=schema.json; done'
